/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MenuComp {}
  interface MenuCompAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'MenuComp': Components.MenuComp;
  }

  interface StencilIntrinsicElements {
    'menu-comp': Components.MenuCompAttributes;
  }


  interface HTMLMenuCompElement extends Components.MenuComp, HTMLStencilElement {}
  var HTMLMenuCompElement: {
    prototype: HTMLMenuCompElement;
    new (): HTMLMenuCompElement;
  };

  interface HTMLElementTagNameMap {
    'menu-comp': HTMLMenuCompElement
  }

  interface ElementTagNameMap {
    'menu-comp': HTMLMenuCompElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
